import React from 'react'

const SafarPlaces = () => {
  return (
    
<div className="SafarPlaces" style={{width: 1440, height: 4685, position: 'relative', background: '#FBF9F9', borderRadius: 8, overflow: 'hidden'}}>
  <div className="Group20" style={{width: 1440, height: 800, left: 0, top: 0, position: 'absolute'}}>
    <div className="Rectangle1" style={{width: 784, height: 66.80, left: 60, top: 22, position: 'absolute', opacity: 0.60, borderRadius: 45}}></div>
    <img className="UnsplashANvhpka9rk" style={{width: 1440, height: 800, left: 0, top: 0, position: 'absolute'}} src="https://via.placeholder.com/1440x800" />
    <div className="DiscoverTheBestPlacesWelcome" style={{width: 821, height: 205, left: 309, top: 330, position: 'absolute', textAlign: 'center', color: 'white', fontSize: 100, fontFamily: 'Times New Roman', fontWeight: '400', wordWrap: 'break-word'}}>Discover The Best <br/>Places Welcome!<br/></div>
    <div className="ForAVeryLowCostVisitEveryBeautifulPlaceOnThePlanetTheAscentToTheSummitOfTheLocationIsNeverLengthierThanYouExpect" style={{width: 821, height: 101, left: 309, top: 574, position: 'absolute', textAlign: 'center', color: 'white', fontSize: 30, fontFamily: 'Times New Roman', fontWeight: '400', wordWrap: 'break-word'}}>For a very Low Cost, visit every beautiful place on the planet. The ascent to the summit of the location is never lengthier than you expect</div>
    <div className="Group22" style={{width: 699, height: 50, left: 60, top: 30, position: 'absolute'}}>
      <div className="Home" style={{width: 150, height: 50, left: 0, top: 0, position: 'absolute', color: 'white', fontSize: 32, fontFamily: 'Times New Roman', fontWeight: '400', wordWrap: 'break-word'}}>Home</div>
      <div className="Blog" style={{width: 150, height: 50, left: 366, top: -0, position: 'absolute', color: 'white', fontSize: 32, fontFamily: 'Times New Roman', fontWeight: '400', wordWrap: 'break-word'}}>Blog</div>
      <div className="AboutUs" style={{width: 150, height: 50, left: 549, top: 0, position: 'absolute', color: 'white', fontSize: 32, fontFamily: 'Times New Roman', fontWeight: '400', wordWrap: 'break-word'}}>About Us</div>
      <div className="Places" style={{width: 150, height: 50, left: 183, top: -0, position: 'absolute', color: 'white', fontSize: 32, fontFamily: 'Times New Roman', fontWeight: '400', wordWrap: 'break-word'}}>Places</div>
    </div>
  </div>
  <div className="Frame22" style={{width: 409, height: 82, left: 469, top: 835, position: 'absolute', justifyContent: 'center', alignItems: 'center', display: 'inline-flex'}}>
    <div className="Frame21" style={{flex: '1 1 0', alignSelf: 'stretch', paddingTop: 21, paddingBottom: 21, paddingLeft: 17, paddingRight: 25, background: '#D9D9D9', justifyContent: 'flex-start', alignItems: 'flex-start', display: 'inline-flex'}}>
      <div className="Vector" style={{width: 35, height: 40, background: 'black'}}></div>
      <div className="StartYourSearch" style={{width: 332, height: 40, textAlign: 'center', color: 'black', fontSize: 36, fontFamily: 'Times New Roman', fontWeight: '400', wordWrap: 'break-word'}}>Start Your Search</div>
    </div>
  </div>
  <div className="Frame21" style={{width: 1336, height: 2713, left: 60, top: 1051, position: 'absolute'}}>
    <img className="Paris" style={{width: 300, height: 450, left: 0, top: 0, position: 'absolute', borderRadius: 300}} src="https://via.placeholder.com/300x450" />
    <img className="Dubai" style={{width: 300, height: 450, left: 659, top: 0, position: 'absolute', borderRadius: 300}} src="https://via.placeholder.com/300x450" />
    <div className="ParisFranceTheCityOfLightRenownedForTheEiffelTowerRomanticAmbianceIconicArtAndVibrantCulture" style={{width: 255, height: 255, left: 348, top: 97, position: 'absolute', textAlign: 'center'}}><span style="color: 'black', fontSize: 36, fontFamily: 'Times New Roman', fontWeight: '400', wordWrap: 'break-word'">Paris ,France<br/><br/></span><span style="color: 'black', fontSize: 24, fontFamily: 'Times New Roman', fontWeight: '400', wordWrap: 'break-word'">The "City of Light," renowned for the Eiffel Tower, romantic ambiance, iconic art, and vibrant culture.<br/></span></div>
    <div className="DubaiUaeAFuturisticCityFamousForBurjKhalifaLuxuryShoppingDesertSafarisAndWorldClassArchitecture" style={{width: 255, height: 255, left: 1040, top: 95, position: 'absolute', textAlign: 'center'}}><span style="color: 'black', fontSize: 36, fontFamily: 'Times New Roman', fontWeight: '400', wordWrap: 'break-word'">Dubai, UAE<br/><br/></span><span style="color: 'black', fontSize: 24, fontFamily: 'Times New Roman', fontWeight: '400', wordWrap: 'break-word'">A futuristic city famous for Burj Khalifa, luxury shopping, desert safaris, and world-class architecture.</span></div>
    <div className="JaipurIndiaKnownAsThePinkCityItBoastsMajesticPalacesVibrantBazaarsAndRichRajasthaniCulture" style={{width: 255, height: 255, left: 348, top: 838, position: 'absolute', textAlign: 'center'}}><span style="color: 'black', fontSize: 36, fontFamily: 'Times New Roman', fontWeight: '400', wordWrap: 'break-word'">Jaipur, India<br/></span><span style="color: 'black', fontSize: 50, fontFamily: 'Times New Roman', fontWeight: '400', wordWrap: 'break-word'"><br/></span><span style="color: 'black', fontSize: 24, fontFamily: 'Times New Roman', fontWeight: '400', wordWrap: 'break-word'">Known as the "Pink City," it boasts majestic palaces, vibrant bazaars, and rich Rajasthani culture.</span></div>
    <img className="UnsplashPcxkjrb8fw" style={{width: 300, height: 500, left: 0, top: 673, position: 'absolute', borderRadius: 300}} src="https://via.placeholder.com/300x500" />
    <div className="AgraIndiaHomeToTheTajMahalAUnescoWorldHeritageSiteAndSymbolOfEternalLove" style={{width: 255, height: 255, left: 1040, top: 838, position: 'absolute', textAlign: 'center'}}><span style="color: 'black', fontSize: 36, fontFamily: 'Times New Roman', fontWeight: '700', wordWrap: 'break-word'">Agra, India     <br/></span><span style="color: 'black', fontSize: 24, fontFamily: 'Times New Roman', fontWeight: '400', wordWrap: 'break-word'">Home to the Taj Mahal, a UNESCO World Heritage site and symbol of eternal love.</span></div>
    <img className="UnsplashLfvqjziyrwc" style={{width: 300, height: 500, left: 668, top: 673, position: 'absolute', borderRadius: 300}} src="https://via.placeholder.com/300x500" />
    <img className="UnsplashIhHksr5o7c" style={{width: 300, height: 500, left: 0, top: 1396, position: 'absolute', borderRadius: 300}} src="https://via.placeholder.com/300x500" />
    <div className="TokyoJapanABustlingMetropolisBlendingCuttingEdgeTechnologyAncientTemplesAndUniqueCulinaryExperiences" style={{width: 255, height: 255, left: 348, top: 1518, position: 'absolute', textAlign: 'center'}}><span style="color: 'black', fontSize: 36, fontFamily: 'Times New Roman', fontWeight: '700', wordWrap: 'break-word'">Tokyo, Japan     <br/></span><span style="color: 'black', fontSize: 36, fontFamily: 'Times New Roman', fontWeight: '400', wordWrap: 'break-word'">A bustling </span><span style="color: 'black', fontSize: 24, fontFamily: 'Times New Roman', fontWeight: '400', wordWrap: 'break-word'">metropolis blending cutting-edge technology, ancient temples, and unique culinary </span><span style="color: 'black', fontSize: 36, fontFamily: 'Times New Roman', fontWeight: '400', wordWrap: 'break-word'">experiences.</span></div>
    <img className="UnsplashNfsb3jpvlcm" style={{width: 300, height: 500, left: 668, top: 1396, position: 'absolute', borderRadius: 300}} src="https://via.placeholder.com/300x500" />
    <div className="VaranasiIndiaTheSpiritualHeartOfIndiaOfferingSacredGangesGhatsAndProfoundHinduRituals" style={{width: 255, height: 255, left: 1040, top: 1516, position: 'absolute', textAlign: 'center'}}><span style="color: 'black', fontSize: 36, fontFamily: 'Times New Roman', fontWeight: '700', wordWrap: 'break-word'">Varanasi, India     <br/></span><span style="color: 'black', fontSize: 24, fontFamily: 'Times New Roman', fontWeight: '400', wordWrap: 'break-word'">The spiritual heart of India, offering sacred Ganges ghats and profound Hindu rituals.</span></div>
    <div className="NewYorkUsaTheBigAppleIconicForItsSkylineTimesSquareAndDiverseCulturalMeltingPot" style={{width: 255, height: 255, left: 348, top: 2267, position: 'absolute', textAlign: 'center'}}><span style="color: 'black', fontSize: 36, fontFamily: 'Times New Roman', fontWeight: '700', wordWrap: 'break-word'">New York  USA<br/><br/></span><span style="color: 'black', fontSize: 24, fontFamily: 'Times New Roman', fontWeight: '400', wordWrap: 'break-word'">The "Big Apple," iconic for its skyline, Times Square, and diverse cultural melting pot.     </span></div>
    <img className="Unsplash5omwamdxmku" style={{width: 300, height: 500, left: 0, top: 2119, position: 'absolute', borderRadius: 300}} src="https://via.placeholder.com/300x500" />
    <div className="VeniceItalyARomanticCityOfCanalsGondolasHistoricArchitectureAndBreathtakingSunsetsOverTheLagoon" style={{width: 255, height: 255, left: 1040, top: 2241, position: 'absolute', textAlign: 'center'}}><span style="color: 'black', fontSize: 36, fontFamily: 'Times New Roman', fontWeight: '700', wordWrap: 'break-word'">Venice, Italy     <br/></span><span style="color: 'black', fontSize: 24, fontFamily: 'Times New Roman', fontWeight: '400', wordWrap: 'break-word'">A romantic city of canals, gondolas, historic architecture, and breathtaking sunsets over the lagoon</span></div>
    <img className="Unsplash41l0wlggvi" style={{width: 300, height: 500, left: 668, top: 2145, position: 'absolute', borderRadius: 300}} src="https://via.placeholder.com/300x500" />
  </div>
  <div className="Group15" style={{width: 1442, height: 776, left: -2, top: 3909, position: 'absolute'}}>
    <div className="Rectangle12" style={{width: 1440, height: 776, left: 0, top: 0, position: 'absolute', background: 'rgba(74.84, 150.21, 171.06, 0.10)'}} />
    <div className="SubscribeForFreshContectProductUpdate" style={{width: 471, height: 56, left: 70, top: 89, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Times New Roman', fontWeight: '700', wordWrap: 'break-word'}}>SUBSCRIBE FOR FRESH<br/>CONTECT & PRODUCT UPDATE</div>
    <div className="Group15" style={{width: 327, height: 37, left: 70, top: 157, position: 'absolute'}}>
      <div className="Rectangle13" style={{width: 327, height: 37, left: 0, top: 0, position: 'absolute', borderRadius: 25, border: '5px rgba(0, 0, 0, 0.44) solid'}} />
      <div className="EnterYourEmail" style={{width: 182, height: 27, left: 29, top: 5, position: 'absolute', color: 'rgba(0, 0, 0, 0.50)', fontSize: 20, fontFamily: 'Times New Roman', fontWeight: '700', wordWrap: 'break-word'}}>Enter Your Email</div>
    </div>
    <div className="Group16" style={{width: 150, height: 29, left: 70, top: 212, position: 'absolute'}}>
      <div className="Rectangle14" style={{width: 150, height: 29, left: 0, top: 0, position: 'absolute', background: 'white', borderRadius: 25, border: '1px black solid'}} />
      <div className="Subscribe" style={{width: 141, height: 25, left: 9, top: 4, position: 'absolute', textAlign: 'center', color: 'black', fontSize: 22, fontFamily: 'Times New Roman', fontWeight: '700', wordWrap: 'break-word'}}>Subscribe</div>
    </div>
    <div className="Group17" style={{width: 506, height: 220, left: 838, top: 89, position: 'absolute'}}>
      <div className="InformationAboutUsBlogPackageFAQ" style={{width: 150, height: 220, left: 356, top: 0, position: 'absolute'}}><span style="color: 'black', fontSize: 24, fontFamily: 'Times New Roman', fontWeight: '700', wordWrap: 'break-word'">Information<br/><br/></span><span style="color: 'rgba(0, 0, 0, 0.70)', fontSize: 24, fontFamily: 'Times New Roman', fontWeight: '700', wordWrap: 'break-word'">About us<br/>Blog<br/>Package<br/>F.A.Q<br/></span><span style="color: 'black', fontSize: 22, fontFamily: 'Times New Roman', fontWeight: '700', wordWrap: 'break-word'"><br/></span></div>
      <div className="ProductCarHireVisaPackagePassportInsuranceEducation" style={{width: 150, height: 220, left: 178, top: 0, position: 'absolute'}}><span style="color: 'black', fontSize: 24, fontFamily: 'Times New Roman', fontWeight: '700', wordWrap: 'break-word'">Product<br/><br/></span><span style="color: 'rgba(0, 0, 0, 0.70)', fontSize: 24, fontFamily: 'Times New Roman', fontWeight: '700', wordWrap: 'break-word'">Car hire<br/>Visa<br/>Package<br/>Passport<br/>Insurance<br/>Education<br/></span></div>
      <div className="TourAsiaAfricaAmericaChinaHoliday" style={{width: 150, height: 220, left: 0, top: 0, position: 'absolute'}}><span style="color: 'black', fontSize: 24, fontFamily: 'Times New Roman', fontWeight: '700', wordWrap: 'break-word'">Tour <br/></span><span style="color: 'rgba(0, 0, 0, 0.50)', fontSize: 24, fontFamily: 'Times New Roman', fontWeight: '700', wordWrap: 'break-word'"><br/></span><span style="color: 'rgba(0, 0, 0, 0.70)', fontSize: 24, fontFamily: 'Times New Roman', fontWeight: '700', wordWrap: 'break-word'">Asia<br/>Africa<br/>America<br/>China<br/>Holiday<br/></span></div>
    </div>
    <div className="Group18" style={{width: 1442, height: 300, left: 0, top: 409, position: 'absolute'}}>
      <img className="P5" style={{width: 195.92, height: 250, left: 207.68, top: 49, position: 'absolute', borderRadius: 15}} src="https://via.placeholder.com/196x250" />
      <img className="P6" style={{width: 195.92, height: 300, left: 830.72, top: -0, position: 'absolute', borderRadius: 15}} src="https://via.placeholder.com/196x300" />
      <img className="P7" style={{width: 195.92, height: 250, left: 1038.40, top: 50, position: 'absolute', borderRadius: 15}} src="https://via.placeholder.com/196x250" />
      <img className="P4" style={{width: 195.92, height: 300, left: 415.36, top: -0, position: 'absolute', borderRadius: 15}} src="https://via.placeholder.com/196x300" />
      <img className="P3" style={{width: 195.92, height: 300, left: 1246.08, top: -0, position: 'absolute', borderRadius: 15}} src="https://via.placeholder.com/196x300" />
      <img className="P2" style={{width: 195.92, height: 250, left: 623.04, top: 50, position: 'absolute', borderRadius: 15}} src="https://via.placeholder.com/196x250" />
      <img className="P1" style={{width: 195.92, height: 300, left: 0, top: 0, position: 'absolute', borderRadius: 15}} src="https://via.placeholder.com/196x300" />
    </div>
  </div>
  <div className="Safar" style={{width: 150, left: 1235, top: 8, position: 'absolute', color: 'white', fontSize: 60, fontFamily: 'Times New Roman', fontWeight: '700', wordWrap: 'break-word'}}>Safar</div>
</div>

)
}

export default SafarPlaces